spring.kafka.consumer.properties.spring.json.trusted.packages=*

my.kafka.address=localhost:9092
my.kafka.in.topic=messages
my.kafka.out.topic.prefix=filtered_messages_
my.kafka.blocked.users.topic=blocked_users
my.kafka.blocked.users.store=blocked_users
my.users.number=4