spring.kafka.consumer.properties.spring.json.trusted.packages=*

my.kafka.address=localhost:9092
my.kafka.in.topic=word_topic_in
my.kafka.out.topic.prefix=word_topic_out_
my.kafka.blocked.users.topic=blocked_users
my.users.number=4